// Code generated by mockery v1.0.0. DO NOT EDIT.
package storage

import mock "github.com/stretchr/testify/mock"

// MockBookingStorage is an autogenerated mock type for the BookingStorage type
type MockBookingStorage struct {
	mock.Mock
}

// CreateBooking provides a mock function with given fields: booking
func (_m *MockBookingStorage) CreateBooking(booking *Booking) error {
	ret := _m.Called(booking)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
